spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anonymous-Chris/microservices-config-repo.git
          skip-ssl-validation: true
          clone-on-start: true
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
